### ISSUE TITLE
AddAddress not allowed in repeated's core conditions

### ISSUE THREAD

**Issue by gdeOo** [Jamiras/RATools#150]
```
function f(n) => byte(byte(0x9999)) == 9 && byte(0x1111) == n

achievement("t", "d", 5,
    once(f(1) || f(2))
)
```

The or'd groups inside the `once` call share the `byte(byte(0x9999)) == 9` condition, which contains an `AddAddress` instruction. This scenario is not contemplated when `RepeatedFunction::EvaluateAddHits` tries to generate instructions for the core conditions, issuing the following error: `modifier not allowed in multi-condition repeated clause`.

Only the `AndNext` flag is allowed through, even though I'm almost sure `AddAddress`, `AddSource` and `SubSource` should also be allowed. Seems like an oversight in the implementation of #129.

**Comment by Jamiras** [comment]
Each of the flags is allowed individually and there are unit tests for them. The problem here has to do with the common clause being promoted to the core. If you change it to:
```
function f(n) => byte(byte(0x9999)) == n && byte(0x1111) == n

achievement("t", "d", 5,
    once(f(1) || f(2))
)
```
then it's fine. The [`IsCombining` check](https://github.com/Jamiras/RATools/pull/129/files#diff-7256cc85b27319dc41aa0ed109fbb784R122) should allow the items you've enumerated. The problem lies in the validation for the Core group where similar logic needs to be applied.
