### ISSUE TITLE
Non-equal alt groups mistakenly merged during optimization

### ISSUE THREAD

**Issue by gdeOo** [Jamiras/RATools#154]
```
achievement("t", "d", 5,
    repeated(2, once(byte(0x1111) == 1 && byte(0x2222) == 0)
                || once(byte(0x1111) == 2 && byte(0x2222) == 0))
)

// compiles to
AndNext byte(0x001111) == 2
repeated(2, byte(0x002222)) == 0
```

Notice that the first "alt group" inside the `repeated` call is not converted into an `AddHits`. It is completely removed instead.

I tracked this down to an issue during optimization. `MergeDuplicateAlts > MergeRequirements` mistakenly determines that both alt groups are equal, because the final condition (`byte(0x2222) == 0`) is the same, and removes the first one.

**Comment by Jamiras** [comment]
`MergeRequirements` is making an assumption that all but the last requirement are modifiers (AddSource, SubSource, AddAddress), which don't have a right side. When checking for mergability of the example you've provided, since the left side of the AndNext statements are equivalent, they're considered mergable.
