### ISSUE TITLE
Include Core as a submodule

### ISSUE THREAD

**Issue by rzumer** [Jamiras/RATools#16]
It seems logical, unless there is a particular reason not to.

Fetching the other dependencies automatically via nuget or some other method and referencing them by default would be nice too.

**Comment by Jamiras** [comment]
I can't decide if I want to do this or not. 

As long as the nUnit and Moq dlls still have to be manually downloaded, I would expect most users to also download the Core dll, rather than build their own - although that assumes that the latest published Core dll contains all the changes referenced by the current master.

The primary reason it's set up like this is that I use the Core dll and libs folders for other projects, so it's convenient for me.

Making Core a submodule makes sense assuming others are going to be doing development, or using pre-released builds, but doesn't solve the libs issue. I suppose I could make them a submodule too, but git isn't designed for binary files. It's probably not that important as I've only updated them once in five years :P

**Comment by Jamiras** [comment]
I chose to write a batch file to download the nUnit dlls - it's run as a pre-build step for Core.Tests.dll.
