### ISSUE TITLE
[Enhancement] Clearer message for "Cannot convert to an address" error

### ISSUE THREAD

**Issue by MagmarFire** [Jamiras/RATools#182]
In my goal of calculating pointer offsets, I've encountered an issue where certain operations do not seem to allow me to use offsets at all. However, it's unclear why this is, where my error lies, and what steps I can take to remedy the issue. It would be helpful if the error message in question provided more detail as to why pointer arithmetic cannot be used in certain situations and what can be done as an alternative.

I have a _potential_ workaround to this with another address I could use, but there's no guarantee that it will always work, so it's ultimately suboptimal.

I have provided a copy of my script that demonstrates a case where a more-descriptive error message would be helpful. (The function that handles the actual offset calculation is on line 2177.)

[World Ends with You, The - Copy.rascript.txt](https://github.com/Jamiras/RATools/files/4935463/World.Ends.with.You.The.-.Copy.rascript.txt)

**Comment by Jamiras** [comment]
The error is generated because `p3PinState` evaluates an expression that would have a negative value for AddAddress. (0x396470 is less than `tinPinOffsetConstant` [0x39B7F8]).

Now that the error list reports multiple levels, I've modified the code that tries to report the most relevant error to include both the originating error and the causative error. This allows for more informative locating of the problematic issue. I've also expanded the error to report the expression it's having issue converting.

![image](https://user-images.githubusercontent.com/32680403/88365605-d3509d00-cd43-11ea-85c5-da49cfd27d3b.png)

In this particular case, I believe it is safe to allow negative AddAddress offsets by using overflow addition. (-21354 would become +0xFFFFD6EC), but I want to do some additional testing first. I will hold off opening a PR until I complete that investigation.

**Comment by Jamiras** [comment]
I have verified that the runtime will properly handle the overflow when evaluating the negative offset, but the editor refuses to allow a value larger than the available address space to be put into the field (i.e. 0xFFFFD6EC > 0x02000000 [maximum valid NDS address]). Additional changes will have to be made to the DLL to allow the value there. For now, I'm leaving this as an error in RATools, but have changed the error message to indicate that the subtraction is not supported.
