### ISSUE TITLE
[Enhancement] Automatically convert comparisons between pointers

### ISSUE THREAD

**Issue by MagmarFire** [Jamiras/RATools#183]
I recently found out that certain comparisons between pointers is not supported. Please refer to the image below (note that the `p1PPGained()`, `p2PPGained()`, etc., functions are indirect pointers):

![image](https://user-images.githubusercontent.com/5499519/87806372-c48a5780-c824-11ea-8c3f-f0d515c76dcc.png)

It took me a while to figure out, but as it turns out, I can have it work as expected when I convert each comparison to a subtraction and see if the result is greater than 0, like so:

![image](https://user-images.githubusercontent.com/5499519/87806553-0fa46a80-c825-11ea-816e-19c132911492.png)

While this workaround is simple enough, a developer would expect the program to do this conversion for them instead of it requiring it to be done manually. It's also suboptimal because it leads to a reduction in code clarity.

I have attached a copy of my script that displays this behavior. Lines 2298 and 2299 are the ones that the program likes, while the uncommented ones, 2296 and 2297, result in the error prompting for the manual conversion.

[World Ends with You, The - Copy.rascript.txt](https://github.com/Jamiras/RATools/files/4938817/World.Ends.with.You.The.-.Copy.rascript.txt)

**Comment by Jamiras** [comment]
Without actually testing because I'm not anywhere near my computer right now, the error is just indicating that pointer on the left side is not the same as the pointer on the right.
```
AddAddress pointer1
           address1 >= address2
```
pointer1 will be added to both addresses. If you have a pointer2 for address 2 that's different from pointer1, there's no valid way to add it just to address2.

Converting it to a SubSource is probably the only valid solution. I'll see how feasible it is to do automatically.
