### ISSUE TITLE
Increased rendering time if a line that's dozens of thousands of characters long moves into view

### ISSUE THREAD

**Issue by MagmarFire** [Jamiras/RATools#191]
I've made an attempt to interface a set of data with a very odd bit width by packing the data I need into a JSON-like string generated from a console application that reads a spreadsheet. In the interest of trying to keep the implementation simple for now, I've not made the application dump a prettified string, electing to just copy and paste it into a dictionary I've named `enemies` whenever I need to redump my spreadsheet for whatever reason down the road. As a result, the single line ends up being very long--over 20,000 characters.

In doing this, I've discovered that RATools seems to take a long time trying to render parts of lines that won't even show up in the viewport anyway due to the lack of horizontal scrollbars. The slowdown is noticeable only when I attempt to scroll the line into view; it does not do this when I look at other lines, and it is not due to the application generating achievement data. It also does not do this if I prettify the JSON object in an app like JSONLint before pasting it into the `enemies` dictionary.

Being able to paste into, and view it as, a single line is desirable, however, because of the inconvenience of having to scroll past a large block of code I can't otherwise collapse from view (related: #161).

I have attached a script that exhibits the behavior. It will be noticeable if you reach the line when you scroll down, but the line itself is 858.

[Kingdom Hearts Recoded - Copy.rascript.txt](https://github.com/Jamiras/RATools/files/5741183/Kingdom.Hearts.Recoded.-.Copy.rascript.txt)

**Comment by Jamiras** [comment]
The problematic line has over 7000 unique highlight regions. When converting this to UI elements, the WPF layout code starts to slow down after ~500 `Run`s, and becomes unresponsive around 1000, even though layout is suspended while updating and many of them won't be visible once the layout is resumed.

As suggested above, since the editor doesn't scroll, I've arbitrarily selected 400 columns as the maximum rendered width. With the window maximized on my 1920x1080 monitor, only about 250 columns are visible, so 400 seems like a reasonable limit.

For this specific line, the result is ~100 `Run`s, and the editor remains responsive.
