### ISSUE TITLE
Wrong never condition is optimized away

### ISSUE THREAD

**Issue by gdeOo** [Jamiras/RATools#196]
Working on `1.7.0`, specifically commit `9a7fe0c05b93f89657a7bc3f038d1c3b458e063c`.

In the following achievement, there are two `never` conditions on address `0x2`. Even though the first one is the most specific condition, it gets optimized away and only the second `never` is kept. It should be optimized the other way round, if I'm not mistaken.

```
achievement("t", "d", 5,
    once(byte(0x1) == 1)
    && never(byte(0x2) != 12)
    && never(byte(0x2) == 0)
)
```

![image](https://user-images.githubusercontent.com/623942/107128453-bf225680-68b5-11eb-9164-fbda56fbbf5f.png)

**Comment by Jamiras** [comment]
The optimizer is seeing two comparisons to `byte(0x2)`: one that says all values that are "not 12" and one that says "only value 0". Since "only value 0" is a subset of "not 12", it's kept and the "not 12" is discarded. For truthiness, the more restrictive condition is required.  I'll modify the code to keep the less restrictive condition when merging `ResetIf`s.
