### ISSUE TITLE
[Bug] RATools doesn't recognize a commutative operation as valid

### ISSUE THREAD

**Issue by MagmarFire** [Jamiras/RATools#213]
I've discovered an interesting issue where RATools throws a "Cannot generate trigger from IntegerConstant" error when I have the following code:

`function IsOnFloor(floor) => floor == floor() + 1`

However, it compiles perfectly fine if I change it to this:

`function IsOnFloor(floor) => floor() + 1 == floor`

The == operator is commutative, and so both expressions are expected to be equivalent.

I have attached a version of the script that demonstrates the behavior.
[Kingdom Hearts Chain of Memories.rascript.txt](https://github.com/Jamiras/RATools/files/6308233/Kingdom.Hearts.Chain.of.Memories.rascript.txt)

**Comment by Jamiras** [comment]
It's a problem with the order things are happening. To consolidate the constants, all integers are moved to the right hand side of the equation and combined there. The singular integer on the left side is ignored as nothing would be left if it were moved to the right side. Later, whatever constant remains on the right side is moved back to the left as an Add/SubSource. The error comes because the generator isn't expecting "integer SubSource integer".
