### ISSUE TITLE
[Enhancement] Allow scripts that don't have a valid ID to be loaded

### ISSUE THREAD

**Issue by MagmarFire** [Jamiras/RATools#225]
As a developer, I want to be able to load a script that may not have a valid game ID so that I can still be able to lint code and fix any script errors.

It's sometimes beneficial to be able to load scripts without valid IDs in RATools, such as in cases where the script file itself is just a utility library that stores functions and the like that I intend to use in multiple games. I understand that the reason for this is likely so the developer doesn't publish any code to a game that doesn't exist and so that it knows what old achievement code to compare the current code to, among other things, but I feel the ability to at least see if the achievements would otherwise compile would be worth at least having some functions be disabled until an actual game ID is specified.

**Comment by Jamiras** [comment]
The main reason for putting an ID in the script is so it knows which `XXX-User.txt` file to write to.

You can always provide a dummy id:
```
// #ID = 99999999
```
It'll say it can't find the game, so you won't be able to write the XXX-User.txt file, but it'll load and run the script just as you've requested.

You just can't specify `#ID=0`, because that results in the same logic as not finding the ID at all.
