### ISSUE TITLE
[Bug] Stack overflow when chaining logical expressions numerous times (by the looks of it)

### ISSUE THREAD

**Issue by MagmarFire** [Jamiras/RATools#243]
I'm writing a function whose aim is to determine whether or not the player has only a select few types of whitelisted commands equipped in their Command Deck in order to impose restriction challenges. The intent is to make it simple enough to set up so that it can be used multiple times. In addition to this, I've attempted to optimize it to chunk off specific command IDs into what I call "clusters" in order to reduce the number of conditions--important due to the possibility of a large number of different commands being whitelisted.

In the attempt to compile it, however, RATools crashes, and running it in Visual Studio indicates that it is due to a stack overflow that ultimately breaks on `FunctionDefinitionExpression::IsAnonymousFunctionName:647`. I suspect this may be due to all the iterations I'm making--perhaps, for instance, I'm attempting to optimize more than I should--but the application should still ideally gracefully throw an error before it gets to that point instead of crashing so that I have a better idea of how I should update my code.

I've not yet attempted to de-engineer the function to see if that simplifies the number of recursive calls required, but it still would be helpful to have this issue alleviated in case this occurs again in another situation.

I have attached a copy of the script that demonstrates the behavior.

[Kingdom Hearts Birth by Sleep Final Mix.rascript.txt](https://github.com/Jamiras/RATools/files/7134226/Kingdom.Hearts.Birth.by.Sleep.Final.Mix.rascript.txt)

**Comment by Jamiras** [comment]
It's not actually recursive in the script - there's a recursion limit already being enforced there. The stack overflow comes from evaluating the expression generated by the `HasOnlyTheGivenCommandsEquipped` function. The expression tree is very unbalanced, so the recursion caused by processing it crashes the application.

The problem is exacerbated by the `always_true()` and `always_false()` helper objects used to construct the logic chains. Unfortunately, those still exist in the expression tree, and get compounded when creating the cross-product of conditions to handle all of the potential combinations resulting from ANDing ORed groups together. They don't disappear until the achievement is finally compiled to "mem" syntax.

I made some changes to eliminate the helper `always_true()` and `always_false()` functions earlier in the process, which eliminates the crash, but the resulting trigger for "Sleeping Death [m]" was over 300KB in serialized form (768 alts with ~20 conditions each). Something still would need to have been done to simplify that into the 64KB limit.

Unfortunately, that cannot be the final solution, as `always_true()` and `always_false()` are sometimes used to separate ResetIfs from PauseIfs, so prematurely eliminating them breaks several existing scripts. I'll think about other options.
