### ISSUE TITLE
Recent files list parses \r incorrectly?

### ISSUE THREAD

**Issue by rzumer** [Jamiras/RATools#25]
![image](https://user-images.githubusercontent.com/7488362/52722735-3ef0e100-2f7a-11e9-977f-9f8e38368a28.png)

My username is `rzumer`, but it seems like the list is parsing `\r` as a carriage return. Loading from the list does not work either. On the other hand when loading a new file the entry is populated correctly, so it must have something to do with the persistence/serialization model.

**Comment by Jamiras** [comment]
The escaping algorithm was only handling "\r" and "\n". It was not handling "\", so "\rzumer" was not being escaped to "\\rzumer", resulting in the unescaping code converting the "\r" of the path into a carriage return.

If you want to keep your recent items after uptaking this change, you'll have to manually edit your `%APPDATA%/Roaming/Jamiras/RATools\userdata.ini` and do a search and replace of "\" with "\\". Otherwise, old entries will be incorrect. New entries will be correct, so you can also update your list by opening items you want to re-add to the recent items.
