### ISSUE TITLE
Non-standard operator precedence

### ISSUE THREAD

**Issue by rzumer** [Jamiras/RATools#34]
It seems like the division operator has precedence over multiplication, or perhaps operators are processed from right to left, as I get integers rounded down to 0 when returning `some_large_value * 30 / 60` from a function.

**Comment by Jamiras** [comment]
When building the expression tree, it is initially right-heavy.

```
    *
sv      /
     30   60
```

There's rebalancing logic that ensures multiplication and division happen before addition and subtraction, but nothing was regulating priority between multiplication and division. The "30/60" was being evaluated first, which due to integer rounding resulted in 0, which was then multiplied with the large value.

I've modified the code to also rebalance operations with the same priority so they will be evaluated left-to-right.
