### ISSUE TITLE
[Feature Request] Variables as default parameter values

### ISSUE THREAD

**Issue by wescopeland** [Jamiras/RATools#395]
I have the following function definition:

```
function BossKill(bossKey, bossDeadHealth = 0, requiredCheckpoint = 0xCC) { ... }
```

The snippet above works. However, this snippet does not:

```
Foo = 0xCC
function BossKill(bossKey, bossDeadHealth = 0, requiredCheckpoint = Foo) { ... }
```

I fear if I don't assign `0xCC` to some kind of variable, it'll inevitably become a magic number.

![Capture](https://github.com/Jamiras/RATools/assets/3984985/8653da65-b518-425e-a68a-7874089afd5e)

**Comment by Jamiras** [comment]
While the tooltip error just says "Unknown variable: Foo", the error window further expands on that: "Default value for requiredCheckpoint is not constant"

Semantically, it doesn't make sense for a variable to be assigned to a default parameter. It must be a constant. But RATools doesn't currently support named constants.

However, it does allow that sort of thing when defining dictionaries:
```
d = {
    Foo: "Hello"
}
```
The value is evaluated when the dictionary is constructed. It's probably reasonable to expect the same behavior for default parameters.

**Comment by Jamiras** [comment]
The dictionary gets around this limitation because of the assignment operator. The thing on the right is evaluated before stored in the variable. It just turns out that dictionary construction is similar to making a function call or performing arithmetic.

The code that processes the default parameters for a function doesn't currently evaluate each parameter. It just spits out the error. The solution will be to add the evaluation logic there. I just haven't gotten around to it.

**Comment by Jamiras** [comment]
> Assuming I am interpreting correctly, in this instance, I think I have something going on like what you're describing

I was actually describing this:
```
room_entrance = 1
room_hallway = 2

rooms = {
    room_entrance: "Entrance",
    room_hallway: "Hallway",
}
```
