### ISSUE TITLE
Crash when trying to call a function via dictionary reference

### ISSUE THREAD

**Issue by GauChoob** [Jamiras/RATools#528]
Hello,

I found a crash running on 1.14.1

When accessing a function from a dictionary, I need to first move the function into a variable, and then call the variable. If I try to call the function directly from the dictionary, the program either throws an error or crashes completely.

Please see the attached example .rascript file.

Ideally it would be nice to directly call the function from the dictionary[key] if possible, but at least it would be nice to have the crash fixed! :)

[RATools3.log](https://github.com/user-attachments/files/16987355/RATools3.log)
[crashing.rascript.txt](https://github.com/user-attachments/files/16987381/crashing.rascript.txt)

**Comment by Jamiras** [comment]
You can call functions directly from dictionaries. Your particular script is crashing because of the nested function call within `speedrun`. When it tries to look back through the scopes to find the `achievement` function, it hits the scope for the function embedded in the dictionary, and that's where the exception occurs.
