### ISSUE TITLE
Invalid memory string generated (parse error -6)

### ISSUE THREAD

**Issue by gdeOo** [Jamiras/RATools#96]
I've hit an issue in which RATools compiles a script but generates a mem string that is invalid, yielding a "Parse error -6" when loaded from disk by RAIntegration.

The issue can be reproduced with this script:

```
a1 = bit1(0xabcd)
a2 = bit2(0xabcd)
function count_a() => a1 + a2
b1 = bit3(0xabcd)
b2 = bit4(0xabcd)
function count_b() => b1 + b2

achievement(
    title="Test", description="Test", points=5,
    trigger=never((count_a()) > ((count_b()) + 1))
)
```

The generated mem string is `B:1=0_A:0xN00abcd=0_N:0xO00abcd0x000000_0xP00abcd<=0xQ00abcd`.

Removing the `never` call also yields an invalid mem string, which crashed RAIntegration when loaded.

------

Rewriting the trigger as the functionally equivalent `(count_a() - count_b() > 1)` generates a valid achievement.

**Comment by Jamiras** [comment]
This is the result of having a complex expression on the right hand side of the comparison. 
```
a1 + a2 > b1 + b2 + 1
```
The runtime can only compare to a single memory address or value. As it's trying to move the all the calculations to the lefthand side, something went wrong. The result should have been:
```
a1 + a2 - b1 - b2 > 1
```
Which is effectively your equivalent expression: `count_a() - count(b) > 1`
But the generated string you've provided is:
```
SubSource 1
AddSource bit1(0xabcd)
AndNext   bit2(0xabcd) [?] 0
          bit3(0xabcd) <= bit4(0xabcd)
```
It seems like it chose to move the 1 instead of b2, which would have resulted in:
```
a1 + a2 - b1 - 1 > b2
```
The AndNext is unexpected. The 0x000000 is the right side of the AndNext. There should be an operator between the two parts of the AndNext. The missing operator is causing the Parse Error -6 (RC_INVALID_OPERATOR). 

The AndNext should have been an AddSource and the final condition should have been a SubSource. Additionally, the comparison on the final condition is inverted.

It should be easy enough to fix this problem, but I'm going to have to think some about how to address the underflow.
